// Mock data for development
export const mockUsers = [
    {
        userId: 1,
        username: "john_doe",
        email: "john@example.com",
        trustScore: 95,
        avatar: "https://i.pravatar.cc/150?img=1",
        createdAt: "2024-01-15",
    },
    {
        userId: 2,
        username: "jane_smith",
        email: "jane@example.com",
        trustScore: 88,
        avatar: "https://i.pravatar.cc/150?img=2",
        createdAt: "2024-01-20",
    },
    {
        userId: 3,
        username: "mark_wilson",
        email: "mark@example.com",
        trustScore: 72,
        avatar: "https://i.pravatar.cc/150?img=3",
        createdAt: "2024-02-05",
    },
    {
        userId: 4,
        username: "sarah_jones",
        email: "sarah@example.com",
        trustScore: 91,
        avatar: "https://i.pravatar.cc/150?img=4",
        createdAt: "2024-02-10",
    },
    {
        userId: 5,
        username: "david_brown",
        email: "david@example.com",
        trustScore: 85,
        avatar: "https://i.pravatar.cc/150?img=5",
        createdAt: "2024-02-15",
    },
];

export const mockCategories = [
    {
        categoryId: 1,
        id: 1,
        name: "Quần áo",
        description: "Quần áo mới, như mới",
        color: "#3b82f6",
        icon: "👕",
        itemCount: 45,
    },
    {
        categoryId: 2,
        id: 2,
        name: "Điện tử",
        description: "Thiết bị điện tử",
        color: "#8b5cf6",
        icon: "📱",
        itemCount: 32,
    },
    {
        categoryId: 3,
        id: 3,
        name: "Sách",
        description: "Sách và tài liệu",
        color: "#ec4899",
        icon: "📚",
        itemCount: 28,
    },
    {
        categoryId: 4,
        id: 4,
        name: "Đồ nội thất",
        description: "Bàn ghế, tủ",
        color: "#f59e0b",
        icon: "🛋️",
        itemCount: 18,
    },
    {
        categoryId: 5,
        id: 5,
        name: "Đồ chơi",
        description: "Đồ chơi trẻ em",
        color: "#10b981",
        icon: "🎮",
        itemCount: 24,
    },
    {
        categoryId: 6,
        id: 6,
        name: "Khác",
        description: "Các vật dụng khác",
        color: "#6b7280",
        icon: "📦",
        itemCount: 15,
    },
];

export const mockBadges = [
    {
        id: 1,
        badgeId: 1,
        name: "Nhà từ thiện",
        description: "Người chia sẻ tích cực",
        icon: "❤️",
        requiredPoints: 100,
        userCount: 125,
    },
    {
        id: 2,
        badgeId: 2,
        name: "Người tín nhiệm",
        description: "Điểm tín dùng cao",
        icon: "⭐",
        requiredPoints: 250,
        userCount: 87,
    },
    {
        id: 3,
        badgeId: 3,
        name: "Người giúp đỡ",
        description: "Nhiều lần giúp đỡ người khác",
        icon: "🙏",
        requiredPoints: 150,
        userCount: 156,
    },
    {
        id: 4,
        badgeId: 4,
        name: "Sưu tầm gia",
        description: "Sưu tầm nhiều vật dụng",
        icon: "🎯",
        requiredPoints: 200,
        userCount: 94,
    },
];

export const mockReports = [
    {
        id: 1,
        reportId: 1,
        type: "Spam",
        status: "pending",
        reporter: "john_doe",
        reportedUser: "bad_user_1",
        description: "Bài đăng spam",
        createdAt: "2024-12-25",
    },
    {
        id: 2,
        reportId: 2,
        type: "Inappropriate",
        status: "resolved",
        reporter: "jane_smith",
        reportedUser: "bad_user_2",
        description: "Nội dung không phù hợp",
        createdAt: "2024-12-24",
    },
    {
        id: 3,
        reportId: 3,
        type: "Fraud",
        status: "investigating",
        reporter: "mark_wilson",
        reportedUser: "bad_user_3",
        description: "Gian lận trong giao dịch",
        createdAt: "2024-12-26",
    },
    {
        id: 4,
        reportId: 4,
        type: "Abuse",
        status: "pending",
        reporter: "sarah_jones",
        reportedUser: "bad_user_4",
        description: "Lạm dụng hệ thống",
        createdAt: "2024-12-27",
    },
];

export const mockStatistics = {
    totalUsers: 1234,
    totalTransactions: 5678,
    totalCategories: 12,
    totalReports: 45,
    totalItems: 892,
    userGrowth: [
        { month: "Jan", users: 400 },
        { month: "Feb", users: 520 },
        { month: "Mar", users: 680 },
        { month: "Apr", users: 890 },
        { month: "May", users: 1100 },
        { month: "Jun", users: 1234 },
    ],
    transactionTrend: [
        { day: "Mon", transactions: 240 },
        { day: "Tue", transactions: 320 },
        { day: "Wed", transactions: 280 },
        { day: "Thu", transactions: 350 },
        { day: "Fri", transactions: 420 },
        { day: "Sat", transactions: 540 },
        { day: "Sun", transactions: 145 },
    ],
};
